process iqtree_bootstrap {
    cpus 4
    memory '8 GB'
    time '2h'
    
    // Using a trusted StaphB IQ-TREE container matching your cluster setup
    container 'docker://staphb/iqtree2:latest'
    
    publishDir "${params.output}/bootstrap_tree", mode: 'copy'

    input:
    // This takes the kSNP4 run directory path emitted by your previous step
    path kSNP4_run_dir 

    output:
    path "core_bootstrap.treefile", emit: bootstrap_tree
    path "core_bootstrap.iqtree"  , emit: log_report

    script:
    """
    # Run IQ-TREE 2 directly on the native core FASTA matrix generated by kSNP4
    # -m GTR+G+ASC : GTR model with Gamma rate variation and Ascertainment Bias Correction (+ASC)
    # -B 1000      : 1000 Ultrafast Bootstrap replicates
    iqtree2 \\
        -s ${kSNP4_run_dir}/core_SNPs_matrix.fasta \\
        -m GTR+G+ASC \\
        -B 1000 \\
        -T ${task.cpus} \\
        --prefix core_bootstrap
    """
}
