# Provide absolute path for both  "input" and "output"

input: "/Your-Path-To/samples_fasta"
output : "./output"
krakenSub_db: "/PATH-To/krakendb_subs/leg_subsp_customedDB" # Path to Kraken database of Legionella pneumophila subspecies
ref_genomes_dir: "/PATH-To/reference_genomes" # optional or omit it to skip ANI entirely without crashing/ use it if you have reference genomes and need to calculate ANI
